"""Tests for the CSP-based Minesweeper solver.

The constraint scenarios below are hand-designed and hand-verified (not
generated by random play), so the expected deductions are known ground
truth rather than just "the solver didn't crash."
"""

import numpy as np

from agents.csp_solver import CSPAgent
from environment.minesweeper_env import MinesweeperEnv
from evaluation.metrics import run_episode


def test_csp_identifies_guaranteed_safe_and_mine_cells():
    # Board (rows=3, cols=4), single mines at (0,3) and (2,3):
    #   . . 1 .
    #   . . 2 2
    #   . . 1 .
    # (1,3)=2 has exactly 2 hidden neighbors -> (0,3) and (2,3) are both mines.
    # That resolves (0,2)=1 and (1,2)=2 to 0 remaining mines among their
    # other hidden neighbors, so (0,1), (1,1), (2,1) are all safe.
    board = np.array(
        [
            [-1, -1, 1, -1],
            [-1, -1, 2, 2],
            [-1, -1, 1, -1],
        ]
    )
    agent = CSPAgent(rows=3, cols=4, seed=0)
    agent.update_constraints(board)

    assert agent.known_mines == {(0, 3), (2, 3)}
    assert agent.known_safe == {(0, 1), (1, 1), (2, 1)}


def test_csp_subset_rule_resolves_leftover_cells():
    # Board (rows=2, cols=4), single mine at (1,3):
    #   . . 1 1
    #   . . . .
    # (0,3)=1 constrains {(1,2), (1,3)} to exactly 1 mine.
    # (0,2)=1 constrains {(0,1), (1,1), (1,2), (1,3)} to exactly 1 mine.
    # Since the first set is a subset of the second with equal mine count,
    # the leftover cells (0,1) and (1,1) must both be safe, while (1,2) and
    # (1,3) remain genuinely ambiguous (exactly one of the two is a mine).
    board = np.array(
        [
            [-1, -1, 1, 1],
            [-1, -1, -1, -1],
        ]
    )
    agent = CSPAgent(rows=2, cols=4, seed=0)
    agent.update_constraints(board)

    assert agent.known_safe == {(0, 1), (1, 1)}
    assert (1, 2) not in agent.known_safe and (1, 2) not in agent.known_mines
    assert (1, 3) not in agent.known_safe and (1, 3) not in agent.known_mines


def test_csp_no_crash_on_board_with_no_deductions():
    # A completely hidden board offers no constraints at all.
    board = np.full((5, 5), -1)
    agent = CSPAgent(rows=5, cols=5, num_mines=5, seed=0)
    agent.update_constraints(board)

    assert agent.known_safe == set()
    assert agent.known_mines == set()

    action = agent.choose_action(board)
    assert 0 <= action < 25


def test_csp_probabilities_are_valid():
    board = np.array(
        [
            [-1, -1, 1, -1],
            [-1, -1, 2, 2],
            [-1, -1, 1, -1],
        ]
    )
    agent = CSPAgent(rows=3, cols=4, num_mines=2, seed=0)
    agent.update_constraints(board)
    probabilities = agent.calculate_probabilities(board)

    assert all(0.0 <= p <= 1.0 for p in probabilities.values())
    # Cells already deduced safe/mine should not appear as probabilistic guesses.
    assert not (set(probabilities) & agent.known_safe)
    assert not (set(probabilities) & agent.known_mines)


def test_csp_interacts_correctly_with_minesweeper_env():
    env = MinesweeperEnv(rows=5, cols=5, num_mines=5, seed=1)
    agent = CSPAgent(rows=5, cols=5, num_mines=5, seed=1)

    observation, info = env.reset()
    agent.reset()
    terminated = truncated = False
    steps = 0

    while not (terminated or truncated) and steps < 25:
        action = agent.choose_action(observation)
        assert 0 <= action < 25
        observation, reward, terminated, truncated, info = env.step(action)
        steps += 1

    assert steps > 0


def test_csp_can_complete_episodes_via_run_episode():
    env = MinesweeperEnv(rows=5, cols=5, num_mines=5, seed=2)
    agent = CSPAgent(rows=5, cols=5, num_mines=5, seed=2)

    result = run_episode(env, agent.choose_action, on_episode_start=agent.reset)

    assert result["steps"] > 0
    assert isinstance(result["total_reward"], float)
    assert isinstance(result["won"], bool)


def test_csp_never_contradicts_ground_truth_across_seeds():
    # Soundness check: whatever the CSP deduces as safe must never actually
    # be a mine, and whatever it deduces as a mine must never actually be safe.
    for seed in range(10):
        env = MinesweeperEnv(rows=6, cols=6, num_mines=6, seed=seed)
        agent = CSPAgent(rows=6, cols=6, num_mines=6, seed=seed)
        observation, info = env.reset()
        agent.reset()

        terminated = truncated = False
        steps = 0
        while not (terminated or truncated) and steps < 36:
            agent.update_constraints(observation)
            for r, c in agent.known_safe:
                assert not env.game.mines[r][c]
            for r, c in agent.known_mines:
                assert env.game.mines[r][c]

            action = agent.choose_action(observation)
            observation, reward, terminated, truncated, info = env.step(action)
            steps += 1
