"""Tests for the CSP-based Minesweeper solver.

The constraint scenarios below are hand-designed and hand-verified (not
generated by random play), so the expected deductions are known ground
truth rather than just "the solver didn't crash."
"""

import numpy as np
import pytest

from agents.csp_solver import CSPAgent
from environment.minesweeper_env import MinesweeperEnv
from evaluation.metrics import run_episode


def test_csp_identifies_guaranteed_safe_and_mine_cells():
    # Board (rows=3, cols=4), single mines at (0,3) and (2,3):
    #   . . 1 .
    #   . . 2 2
    #   . . 1 .
    # (1,3)=2 has exactly 2 hidden neighbors -> (0,3) and (2,3) are both mines.
    # That resolves (0,2)=1 and (1,2)=2 to 0 remaining mines among their
    # other hidden neighbors, so (0,1), (1,1), (2,1) are all safe.
    board = np.array(
        [
            [-1, -1, 1, -1],
            [-1, -1, 2, 2],
            [-1, -1, 1, -1],
        ]
    )
    agent = CSPAgent(rows=3, cols=4, seed=0)
    agent.update_constraints(board)

    assert agent.known_mines == {(0, 3), (2, 3)}
    assert agent.known_safe == {(0, 1), (1, 1), (2, 1)}


def test_csp_subset_rule_resolves_leftover_cells():
    # Board (rows=2, cols=4), single mine at (1,3):
    #   . . 1 1
    #   . . . .
    # (0,3)=1 constrains {(1,2), (1,3)} to exactly 1 mine.
    # (0,2)=1 constrains {(0,1), (1,1), (1,2), (1,3)} to exactly 1 mine.
    # Since the first set is a subset of the second with equal mine count,
    # the leftover cells (0,1) and (1,1) must both be safe, while (1,2) and
    # (1,3) remain genuinely ambiguous (exactly one of the two is a mine).
    board = np.array(
        [
            [-1, -1, 1, 1],
            [-1, -1, -1, -1],
        ]
    )
    agent = CSPAgent(rows=2, cols=4, seed=0)
    agent.update_constraints(board)

    assert agent.known_safe == {(0, 1), (1, 1)}
    assert (1, 2) not in agent.known_safe and (1, 2) not in agent.known_mines
    assert (1, 3) not in agent.known_safe and (1, 3) not in agent.known_mines


def test_csp_no_crash_on_board_with_no_deductions():
    # A completely hidden board offers no constraints at all.
    board = np.full((5, 5), -1)
    agent = CSPAgent(rows=5, cols=5, num_mines=5, seed=0)
    agent.update_constraints(board)

    assert agent.known_safe == set()
    assert agent.known_mines == set()

    action = agent.choose_action(board)
    assert 0 <= action < 25


def test_csp_probabilities_are_valid():
    board = np.array(
        [
            [-1, -1, 1, -1],
            [-1, -1, 2, 2],
            [-1, -1, 1, -1],
        ]
    )
    agent = CSPAgent(rows=3, cols=4, num_mines=2, seed=0)
    agent.update_constraints(board)
    probabilities = agent.calculate_probabilities(board)

    assert all(0.0 <= p <= 1.0 for p in probabilities.values())
    # Cells already deduced safe/mine should not appear as probabilistic guesses.
    assert not (set(probabilities) & agent.known_safe)
    assert not (set(probabilities) & agent.known_mines)


def test_csp_interacts_correctly_with_minesweeper_env():
    env = MinesweeperEnv(rows=5, cols=5, num_mines=5, seed=1)
    agent = CSPAgent(rows=5, cols=5, num_mines=5, seed=1)

    observation, info = env.reset()
    agent.reset()
    terminated = truncated = False
    steps = 0

    while not (terminated or truncated) and steps < 25:
        action = agent.choose_action(observation)
        assert 0 <= action < 25
        observation, reward, terminated, truncated, info = env.step(action)
        steps += 1

    assert steps > 0


def test_csp_can_complete_episodes_via_run_episode():
    env = MinesweeperEnv(rows=5, cols=5, num_mines=5, seed=2)
    agent = CSPAgent(rows=5, cols=5, num_mines=5, seed=2)

    result = run_episode(env, agent.choose_action, on_episode_start=agent.reset)

    assert result["steps"] > 0
    assert isinstance(result["total_reward"], float)
    assert isinstance(result["won"], bool)


def test_csp_never_contradicts_ground_truth_across_seeds():
    # Soundness check: whatever the CSP deduces as safe must never actually
    # be a mine, and whatever it deduces as a mine must never actually be safe.
    for seed in range(10):
        env = MinesweeperEnv(rows=6, cols=6, num_mines=6, seed=seed)
        agent = CSPAgent(rows=6, cols=6, num_mines=6, seed=seed)
        observation, info = env.reset()
        agent.reset()

        terminated = truncated = False
        steps = 0
        while not (terminated or truncated) and steps < 36:
            agent.update_constraints(observation)
            for r, c in agent.known_safe:
                assert not env.game.mines[r][c]
            for r, c in agent.known_mines:
                assert env.game.mines[r][c]

            action = agent.choose_action(observation)
            observation, reward, terminated, truncated, info = env.step(action)
            steps += 1


def test_first_move_is_a_uniform_guess_with_no_information():
    """The opening move has nothing to deduce from, so every cell scores alike.

    This is why every CSP episode needs at least one guess, and why its
    first-click death rate matches Random's -- a documented property of the
    agent, so it's pinned here rather than left implicit.
    """
    agent = CSPAgent(rows=5, cols=5, num_mines=5, seed=0)
    all_hidden = [[-1] * 5 for _ in range(5)]

    agent.update_constraints(all_hidden)

    assert agent.find_safe_moves(all_hidden) == []
    assert agent.find_mines() == set()
    probabilities = agent.calculate_probabilities(all_hidden)
    # Every cell is on the board and every one carries the identical estimate.
    assert len(probabilities) == 25
    assert len(set(probabilities.values())) == 1
    assert probabilities[(0, 0)] == pytest.approx(5 / 25)


def test_first_move_spreads_across_cells_over_many_seeds():
    # A uniform guess, not a fixed corner: different seeds must pick different
    # opening cells.
    all_hidden = [[-1] * 5 for _ in range(5)]
    chosen = {CSPAgent(rows=5, cols=5, num_mines=5, seed=s).choose_action(all_hidden) for s in range(40)}

    assert len(chosen) > 1


def test_tie_breaking_is_seeded_random_not_a_function_of_the_board():
    """CSP's *deduction* is deterministic; its choice among equals is not.

    Documented because the methodology copy previously claimed the action was
    "deterministic given the board state", which is false whenever several
    cells are equally safe or equally risky.
    """
    # A board where two separate zero-constraints make several cells provably
    # safe at once, so choose_action has a genuine tie to break.
    board = [
        [0, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1],
        [-1, -1, -1, -1, 0],
        [-1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1],
    ]
    picks = {CSPAgent(rows=5, cols=5, num_mines=5, seed=s).choose_action(board) for s in range(40)}

    assert len(picks) > 1, "expected the tie to be broken differently across seeds"


def test_same_seed_reproduces_the_same_choice():
    # Seeded, so a run is still reproducible -- both halves of the claim.
    board = [
        [0, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1],
        [-1, -1, -1, -1, 0],
        [-1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1],
    ]
    first = CSPAgent(rows=5, cols=5, num_mines=5, seed=7).choose_action(board)
    second = CSPAgent(rows=5, cols=5, num_mines=5, seed=7).choose_action(board)

    assert first == second


def test_constraint_count_discounts_already_deduced_mines():
    # `remaining_count = value - known_mine_neighbors` -- a "1" whose single
    # mine is already known must contribute a 0-count (all-safe) constraint.
    agent = CSPAgent(rows=3, cols=3, num_mines=1, seed=0)
    board = [
        [-1, -1, -1],
        [-1, 1, -1],
        [-1, -1, -1],
    ]
    agent.known_mines.add((0, 0))

    agent.update_constraints(board)

    # With the one mine accounted for, every other neighbour of the "1" is safe.
    safe = set(agent.find_safe_moves(board))
    assert (0, 1) in safe and (2, 2) in safe
    assert (0, 0) not in safe
